CREATE_ROOMS_TABLE = "CREATE TABLE IF NOT EXISTS rooms (id SERIAL PRIMARY KEY , name VARCHAR(250));"
CREATE_TEMPS_TABLE = "CREATE TABLE IF NOT EXISTS temperatures (room_id INTEGER , temperature REAL, date TIMESTAMP , FOREIGN KEY(room_id) REFERENCES rooms(id) ON DELETE CASCADE);"
INSERT_ROOM_RETURN_ID = "INSERT INTO rooms (name) VALUES (%s) RETURNING id;"
INSERT_TEMP = "INSERT INTO temperatures (room_id , temperature , date) VALUES (%s , %s , %s);"
GLOBAL_NUMBER_OF_DAYS = "SELECT COUNT (DISTINCT DATE(date) AS days FROM temperatures);"
GLOBAL_AVG = "SELECT AVG(temperature) as average FROM temperatures;"